var chai = require('chai');
var MockBrowser = require('mock-browser').mocks.MockBrowser;

var helpers = require('../src/helpers')({});

var expect = chai.expect;

var mock = new MockBrowser();
var document = mock.getDocument();

describe('scribe-plugin-drag-and-drop helpers', function(){
    /* This test was generated by the grunt-init plugin */

    it('should identify markers', function() {
        var marker = document.createElement('div');
        marker.classList.add(helpers.constants.INDICATOR_CLASS);
        expect(helpers.isMarkerElement(marker)).to.equal(true);
    })

    it('should identify that an element is not a marker', function() {
        var nonMarker = document.createElement('div');
        expect(helpers.isMarkerElement(nonMarker)).to.equal(false);
    });
});
