var chai = require('chai');
var webdriver = require('selenium-webdriver');
var helpers = require('scribe-test-harness/helpers');

var expect = chai.expect;

var when = helpers.when;
var given = helpers.given;
var givenContentOf = helpers.givenContentOf;

var driver;
before(function () {
    driver = helpers.driver;
});

var scribeNode;
beforeEach(function() {
  scribeNode = helpers.scribeNode;
});

describe('scribe-plugin-drag-and-drop', function(){
    /* This test was generated by the grunt-init plugin */
    givenContentOf("<p>some content</p>", function () {
        it('should fail the test', function() {
            expect(true).to.be(false);
        });
    });
});
